/*
 * This source file was generated by the Gradle 'init' task
 */
package po.db.data_service

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Assertions.assertEquals

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsSayHi() {
        val classUnderTest = Library()
        assertEquals(classUnderTest.someLibraryMethod(), "Say Hi")

    }
}
