/*
 * This source file was generated by the Gradle 'init' task
 */
package po.api.ws_service

import po.api.rest_service.*

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
